services:
  - type: web
    name: intern-trail
    env: node
    buildCommand: npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
